### ISSUE TITLE
UsdlCombinedRecognizer fails on IOS

### ISSUE THREAD

**Issue by christinachimi** [BlinkID/blinkid-flutter#14]
We are seeing the UsdlCombinedRecognizer fail on IOS. Stack trace below. The native result of `documentDataMatch` is a bool from IOS but Android supplies an int (and the flutter code expects an int). Not sure if this is something you want to fix upstream, but I can provide a PR to patch it in the flutter package.

Sample error:

```
2020-10-21 08:56:01.663336-0400 Runner[960:170082] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'bool' is not a subtype of type 'int'
#0      new UsdlCombinedRecognizerResult (package:blinkid_flutter/recognizers/usdl_combined_recognizer.dart:100:69)
#1      UsdlCombinedRecognizer.createResultFromNative (package:blinkid_flutter/recognizers/usdl_combined_recognizer.dart:182:16)
#2      MicroblinkScanner.scanWithCamera (package:blinkid_flutter/microblink_scanner.dart:42:50)
<asynchronous suspension>
#3      TripService.scan (package:gopuff_godrive_v2/services/trip.dart:351:43)
#4      _AgeRestrictedPanelState.selectIdDialog.<anonymous closure>.<anonymous closure> (package:gopuff_godrive_v2/components/delivery/view.dart:1053:30)
#5      _AgeRestrictedPanelState.selectIdDialog.<anonymous closure>.<anonymous closure> (package:gopuff_godrive_v2/components/delivery/view.dart:1051:28)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
#21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
#24     _rootRunUnary (dart:async/zone.dart:1206:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#27     _invoke1 (dart:ui/hooks.dart:265:10)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

**Comment by mijo-gracanin** [comment]
@christinachimi thank you for reporting the issue! @dCubelic will push the upstream fix soon.

**Comment by dCubelic** [comment]
@christinachimi [v5.8.1](https://github.com/BlinkID/blinkid-flutter/releases/tag/v5.8.1) is released now which fixes this issue.

Let us know if you have any problems.

Best regards,
Dominik
