### ISSUE TITLE
Unable to get blinkid work

### ISSUE THREAD

**Issue by fvgarrel** [BlinkID/blinkid-flutter#58]
I want to test the library, but whenever I call .scanWithCamera(), I encounter the following error and the app crashes:

```
D/EGL_emulation(30716): app_time_stats: avg=2465.05ms min=221.63ms max=4708.46ms count=2
E/lIlIllllII.java:22@main(30716): error loading native library
E/lIlIllllII.java:22@main(30716): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/lIlIllllII.java:22@main(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/lIlIllllII.java:22@main(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/lIlIllllII.java:22@main(30716): 	at java.lang.System.loadLibrary(System.java:1661)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.hardware.MicroblinkDeviceManager.<clinit>(line:35)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:3)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/lIlIllllII.java:22@main(30716): 	at android.os.Handler.handleCallback(Handler.java:958)
E/lIlIllllII.java:22@main(30716): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/lIlIllllII.java:22@main(30716): 	at android.os.Looper.loopOnce(Looper.java:205)
E/lIlIllllII.java:22@main(30716): 	at android.os.Looper.loop(Looper.java:294)
E/lIlIllllII.java:22@main(30716): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/lIlIllllII.java:22@main(30716): 	at java.lang.reflect.Method.invoke(Native Method)
E/lIlIllllII.java:22@main(30716): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/lIlIllllII.java:22@main(30716): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/lIlIllllII.java:22@main(30716): error loading native library
E/lIlIllllII.java:22@main(30716): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/lIlIllllII.java:22@main(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/lIlIllllII.java:22@main(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/lIlIllllII.java:22@main(30716): 	at java.lang.System.loadLibrary(System.java:1661)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/lIlIllllII.java:22@main(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/lIlIllllII.java:22@main(30716): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/lIlIllllII.java:22@main(30716): 	at android.os.Handler.handleCallback(Handler.java:958)
E/lIlIllllII.java:22@main(30716): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/lIlIllllII.java:22@main(30716): 	at android.os.Looper.loopOnce(Looper.java:205)
E/lIlIllllII.java:22@main(30716): 	at android.os.Looper.loop(Looper.java:294)
E/lIlIllllII.java:22@main(30716): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/lIlIllllII.java:22@main(30716): 	at java.lang.reflect.Method.invoke(Native Method)
E/lIlIllllII.java:22@main(30716): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/lIlIllllII.java:22@main(30716): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(30716): FATAL EXCEPTION: main
E/AndroidRuntime(30716): Process:, PID: 30716
E/AndroidRuntime(30716): java.lang.UnsatisfiedLinkError: dlopen failed: library "libBlinkID.so" not found
E/AndroidRuntime(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/AndroidRuntime(30716): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime(30716): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(30716): 	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
E/AndroidRuntime(30716): 	at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
E/AndroidRuntime(30716): 	at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
E/AndroidRuntime(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.setLicense(BlinkIDFlutterPlugin.java:105)
E/AndroidRuntime(30716): 	at com.microblink.blinkid.flutter.BlinkIDFlutterPlugin.onMethodCall(BlinkIDFlutterPlugin.java:84)
E/AndroidRuntime(30716): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(30716): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(30716): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(30716): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(30716): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30716): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(30716): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(30716): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(30716): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30716): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(30716): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process (30716): Sending signal. PID: 30716 SIG: 9
```

**Comment by fvgarrel** [comment]
Hey @mparadina, 
oh yes, that worked just fine. Sorry and thank you!
